)))Add files via upload
dataMasterskaya/DreamParser pull request #10
Opened 2023-04-23 19:37 UTC by Saponjyan

first commit

2023-04-23 19:38 UTC, Saponjyan commented
h

2023-04-26 19:18 UTC, PhySci requested changes
Минорные комментарии.

2023-04-26 19:18 UTC, PhySci commented on src/parser/habr.py
> +    response = requests.get(url,headers=headers)
Здесь хорошо бы проверить код ответа. Вдруг придёт не 200?

2023-04-26 19:18 UTC, PhySci commented on src/parser/habr.py
> +    link=url
А для чего так делается?

2023-04-26 19:18 UTC, PhySci commented on src/parser/habr.py
> +        response = requests.get(url,headers=headers)
Здесь бы тоже проверить код ответа

2023-04-26 19:18 UTC, PhySci commented on src/parser/habr.py
> +    for i in links:
Переменную _i_ лучше оставить для счётчиков, а здесь может быть link?

2023-04-26 19:18 UTC, PhySci commented on src/parser/habr.py
> +            logging.info(url,"response ERROR")
Здесь хорошо бы сохранять в лог файл полный текст ошибки.

2023-04-28 12:02 UTC, Saponjyan commented
надеюсь все поправил)

2023-04-28 12:03 UTC, Saponjyan commented
похоже все поправил

2023-04-28 20:44 UTC, PhySci approved these changes
Fine!

2023-04-28 20:48 UTC, PhySci approved these changes
Fine!

2023-04-28 20:48 UTC, merged