First commit
dataMasterskaya/DreamParser pull request #12
Opened 2023-04-25 15:48 UTC by muryulia

@PhySci привет, надеюсь, все так делаю. Первая рабочая, но сырая версия

2023-04-26 19:31 UTC, PhySci requested changes
Всё отлично! Несколько минорных комментариев.

2023-04-26 19:31 UTC, PhySci commented on src/parser/xing.py
> +options = webdriver.ChromeOptions()
Давай инициализацию драйвера вынесем в отдельную функцию.

2023-04-26 19:31 UTC, PhySci commented on src/parser/xing.py
> +  for i in range(len(offer_list)):
В Python можно итерироваться прямо по элементам списка:
```
for i, offer in enumerate(offer_list):
   if ('stunde' in offer.text.lower() ...)
```

2023-04-26 19:31 UTC, PhySci commented on src/parser/xing.py
> +          title = None
Давай здесь и далее все пустые значения будем заменять на пустые строки, а не None.

2023-04-26 19:31 UTC, PhySci commented on src/parser/xing.py
> +
Лишняя пустая строка.

2023-04-26 19:31 UTC, PhySci commented on src/parser/xing.py
> +
Лишняя пустая строка.

2023-04-26 19:31 UTC, PhySci commented on src/parser/xing.py
> +      return err
Вот так не надо делать. Функция всегда должна возвращать один и тот же тип данных.
 В твоём случае - если всё хорошо, то возвращает три строки, а если ошибка - только одно.
  Можно к примеру возвращать три пустые строки. А сообщение об ошибке писать в логгер.

2023-05-01 15:43 UTC, muryulia commented on src/parser/xing.py
> +options = webdriver.ChromeOptions()
готово

2023-05-01 15:43 UTC, muryulia commented on src/parser/xing.py
> +  for i in range(len(offer_list)):
готово

2023-05-01 15:43 UTC, muryulia commented on src/parser/xing.py
> +          title = None
готово

2023-05-01 15:43 UTC, muryulia commented on src/parser/xing.py
> +
готово

2023-05-01 15:43 UTC, muryulia commented on src/parser/xing.py
> +
готово

2023-05-01 15:45 UTC, muryulia commented on src/parser/xing.py
> +      return err
переделала - если ошибка при чтении страницы, то скрипт возвращает 3 пустые строки и пишет в лог сообщение с информацией, на какой странице возникла ошибка, иначе собираем инфу со страницы

2023-05-01 15:48 UTC, muryulia commented
@PhySci, посмотри, плиз новый коммит

2023-06-04 16:49 UTC, PhySci approved these changes

2023-06-04 16:49 UTC, merged