Feature/currency cb rf(oophion n)
dataMasterskaya/DreamParser pull request #19
Opened 2023-08-01 09:53 UTC by OophionN

rename branch

2023-08-01 19:22 UTC, PhySci requested changes
Переименуй, пожалуйста, файл так чтобы в нем не было ver3. Почему бы не назвать его _parser_currency.py_ Сокращение CB не самое очевидное. 
 И перенеси в src/parser как обсуждали ранее.

2023-08-01 19:22 UTC, PhySci commented on script_currency_CB_RF/parser_CB_ver3.py
> +        file_path_with_date = os.path.join('data', f"{file_path}_{now}.csv")
Отлично! Здорово что используешь библиотеку os.path

2023-08-01 19:22 UTC, PhySci commented on script_currency_CB_RF/parser_CB_ver3.py
> +        now = datetime.now().strftime("%Y-%m-%d")
Эту и следующую строчку лучше вынести из блока try-except. Ведь в них нечему ломаться.

2023-08-01 19:22 UTC, PhySci commented on script_currency_CB_RF/parser_CB_ver3.py
> +    import logging
Подними этот импорт на первые строчки, там же где и другие.

2023-08-02 06:49 UTC, OophionN commented on script_currency_CB_RF/parser_CB_ver3.py
> +        file_path_with_date = os.path.join('data', f"{file_path}_{now}.csv")
Спасибо. Открыл ее для себя когда отрабатывал рекомендации Юли, раньше не пользовался. Добавил в подборку на будущее, как понял пока она мне полезна в скриптах.

2023-08-02 06:50 UTC, OophionN commented on script_currency_CB_RF/parser_CB_ver3.py
> +        now = datetime.now().strftime("%Y-%m-%d")
Сделано

2023-08-02 06:50 UTC, OophionN commented on script_currency_CB_RF/parser_CB_ver3.py
> +    import logging
забыл перенести пока тестил. Сделано

2023-08-02 06:56 UTC, OophionN commented
Все замечания отработал, файл в старой директории удалил, саму директорию оставил, так как там есть ридми

2023-08-02 06:56 UTC, closed without merging

2023-08-02 07:10 UTC, PhySci commented
> саму директорию оставил, так как там есть ридми

Директория ради одного файла readme выглядит не очень. Не очень понятно, почему эта папка должна существовать.
 Давай самую важную информацию перенесём в заголовок скрипта, а файл и папку удалим.

2023-08-02 07:36 UTC, OophionN commented
@PhySci Федор, я удалил директорию с README. Общая конструкция ветки соответствует main.