Add files via upload
dataMasterskaya/DreamParser pull request #3
Opened 2023-04-20 15:05 UTC by Saponjyan

linkedin

2023-04-22 11:07 UTC, Saponjyan commented
hg

2023-04-23 14:35 UTC, PhySci requested changes
Нарек, привет!
 Отличный скрипт. Добавил несколько комментариев. В нескольких местах могут быть проблемы с логикой исполнения. По возможности, не делай лишний пустых строк.

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +
Удалить лишние пустые строки между def main() и начало комментариев. Комментарий оформить как многострочный (начинается и заканчивается ``` )

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +    display = Display(visible=0, size=(1920, 1200))
Инициализацию драйвера лучше вынести в отдельную функцию.

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +    # Commented out IPython magic to ensure Python compatibility.
Этот комментарий что-то значит здесь?

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +    try:
Не стоит делать два вложенных try-except. Если внутренний ловит ошибку cont.click(), то что делает внешний?

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +    link=soup.find_all("a",class_="base-card__full-link")
У тебя две переменные, которые обе являются списками (или чем-то подобным). Одна называется link, а другая - links. Здесь легко запутаться. Я бы ожидал, что link - это одна ссылка, а links - список ссылок.  А получается что обе переменные - списки. Давай как-то по-другому их назовём?

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +    def scan(url):
Функцию лучше вынести за пределы main. Так код будет чуть попроще.

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +            logging.info(url,"response ERROR")
Здесь надо поправить логику.
 Если get не выполнится и сработает ошибка, то программа всё равно продолжит выполняться и будет что-то там обрабатывать. Но что это, если get провалился?

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +            company = None
Так как мы извлекаем текстовые данные, то пустые поля лучше заменять на пустую строку, а не None.

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +
Лишняя пустая строка.

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +            y = y.split('Industries')[0]
А как это работает? ты получаешь данные в переменную ind, то в след строчке не используешь её. Вместо этого берёшь переменную _y_ из предыдущего блока.

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +        except:
Аналогично и здесь. В переменную _emp_ что-то складывается, но потом ты берёшь _y_ из предыдущего блока и используешь её.

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +
Две пустые строки противоречат PEP8. Оставь,  пожалуйста, только одну.

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +        try:
А зачем здесь try-except ? Что может пойти не так?

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +        try:
Зачем try-except?

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +
Две пустые строки.

2023-04-23 14:35 UTC, PhySci commented on src/parser/linkedin.py
> +
4 пустые строки. Зачем?

2023-04-28 12:05 UTC, Saponjyan commented
тоже вроде все поправил

2023-04-28 20:24 UTC, PhySci commented
Нарек, ты добавил ещё один файл в корень проекта. Он там совсем не нужен. Удали его, пожалуйста, и внести изменения в файл в папке src.

2023-04-28 20:41 UTC, PhySci approved these changes
Great!

2023-04-28 20:41 UTC, merged