Create branch feature/geekjob
dataMasterskaya/DreamParser pull request #4
Opened 2023-04-20 21:36 UTC by AnnaSaigakova

2023-04-22 10:05 UTC, PhySci requested changes
Отличная работа!
 Оставил несколько минорных комментариев. Они больше про читаемость кода и не влияют на качество работы. 
  После дорабоки можно вливать в main.

2023-04-22 10:05 UTC, PhySci commented on src/parser/__pycache__/utils.cpython-39.pyc
Этот файл надо удалить.

2023-04-22 10:05 UTC, PhySci commented on src/parser/geekjob.py
> +#  Функция для получения текущей и предыдущей даты в виде число-месяц как на сайте
Описание функции должно быть под строкой def rename_date().

2023-04-22 10:05 UTC, PhySci commented on src/parser/geekjob.py
> +    options = webdriver.ChromeOptions()
Вынеси, пожалуйста, инициализацию драйвера в отдельную функцию

2023-04-22 10:05 UTC, PhySci commented on src/parser/geekjob.py
> +    query_list = ['аналитик', 'analyst', 'дата сайентист', 'data scientyst', 'DS']
Кажется в слове scientYst опечатка.

2023-04-22 10:05 UTC, PhySci commented on src/parser/geekjob.py
> +    with open(csv_file, 'w', encoding='utf-8-sig', newline='') as file:
Не очень здорово, что в самом начале программы открывается файл и держится открытым всё время.
Во-первых, большая часть кода с дополнительным отступом.
Во-вторых, с файлом может что-то случится за это время.
И логика работы с файлов "разрывается" - в начале открыли и записали заголовок, а гораздо позже - добавляем записи.

Хорошо бы сделать так, чтобы файл открывался на чтение уже в самом конце программы. То есть ты получила все данные, а потом открыла файл и туда всё записала. Для этого можно хранить результаты работы в какой-то переменной.
  Либо открывать файл каждый раз, когда хочешь добавить туда ещё одну строку, т.е. дописывать данные в файл. В этом случае повторнок открытие в режиме append (буква "а" вместо "w" в функции open )

2023-04-22 10:05 UTC, PhySci commented on src/parser/geekjob.py
> +            if vacancies_num != '':
Вот здесь лучше применить "ранний выход", т.е. проверяешь что vacancies_num пустая и тогда выходишь, а иначе - продолжаешь работу. Так избавишься от одного отступа и сделаешь скрипт более читаемым.

2023-04-22 10:05 UTC, PhySci commented on src/parser/geekjob.py
> +                            logging.error(f"Ошибка при загрузке страницы вакансии {link}")
В таком виде после вывода сообщения об ошибке программа продолжит работать дальше и перейдёт на след строчки. В результате будет очень плохой эффект - страница не была скачена, но она обрабатывается. Либо возникнут ошибки, либо будет смешивание информации с разных вакансии.
 Как поправить: если ошибка загрузки страницы, то переходить к другой странице из списка (команда continue).

2023-04-22 10:05 UTC, PhySci commented on src/parser/geekjob.py
> +                            row = [el if el else None for el in row]
А что делает эта строка?

2023-04-22 10:05 UTC, PhySci commented on src/parser/geekjob.py
> +    driver.close()
Зачем драйвер закрывается второй раз (см. строку 236)?

2023-04-24 06:24 UTC, AnnaSaigakova commented on src/parser/__pycache__/utils.cpython-39.pyc
Файл удалила

2023-04-24 06:25 UTC, AnnaSaigakova commented on src/parser/geekjob.py
> +#  Функция для получения текущей и предыдущей даты в виде число-месяц как на сайте
Перенесла описание

2023-04-24 06:26 UTC, AnnaSaigakova commented on src/parser/geekjob.py
> +    options = webdriver.ChromeOptions()
Инициализацию драйвера вынесла в функцию init_driver()

2023-04-24 06:26 UTC, AnnaSaigakova commented on src/parser/geekjob.py
> +    query_list = ['аналитик', 'analyst', 'дата сайентист', 'data scientyst', 'DS']
Да, исправила

2023-04-24 06:26 UTC, AnnaSaigakova commented on src/parser/geekjob.py
> +    with open(csv_file, 'w', encoding='utf-8-sig', newline='') as file:
Перенесла запись в файл в конец программы

2023-04-24 06:27 UTC, AnnaSaigakova commented on src/parser/geekjob.py
> +            if vacancies_num != '':
Поправила

2023-04-24 06:27 UTC, AnnaSaigakova commented on src/parser/geekjob.py
> +                            row = [el if el else None for el in row]
Бесполезная строка, удалила

2023-04-24 06:29 UTC, AnnaSaigakova commented on src/parser/geekjob.py
> +                            logging.error(f"Ошибка при загрузке страницы вакансии {link}")
Совершенно логичное и справедливое замечание. 
Но когда я добавляю continue в блок except, происходит вот что: если запустить парсер с датой 20 апреля (python geekjob.py --parse_date 2023-04-20 - за эту дату есть вакансия, убранная в архив, и на ее страничке отсутствуют данные) в лог-файл записывается нужная строка “Ошибка при загрузке страницы вакансии…”, и потом программа завершает работу с кучей ошибок (хотя по логике должна перейти к следующей по списку вакансии). А если оставить без continue, то все работает: ошибка записывается в лог, и программа идет дальше парсить вакансии, как ни странно. Пробовала сделать через else для блока try-except – такая же картина. Найти логическое объяснение этому у меня не получилось, и т.к. программа отрабатывает корректно без continue, не стала ничего менять. Но вообще, странно и не понятно, почему так происходит.

2023-04-24 06:31 UTC, AnnaSaigakova commented on src/parser/geekjob.py
> +    driver.close()
Первый driver.close() находится внутри цикла прохода по вакансиям и закрывает вкладку с загруженной страницей вакансии, а после цикла в самом конце закрывает основное окно программы. Второй driver.close() исправила на driver.quit(), т.к. после парсинга завершаем всю работу с браузером.

2023-04-28 20:46 UTC, PhySci approved these changes
Great!

2023-04-28 20:46 UTC, merged