Feature/parser vseti
dataMasterskaya/DreamParser pull request #6
Opened 2023-04-21 19:49 UTC by EkaterinaTerentyeva

2023-04-22 08:54 UTC, PhySci requested changes
В целом, скрипт очень сеньёрный. Есть несколько минорных комментариев, которые хорошо бы поправить. Но они не влияют на качество кода, скорее про снижение когнитивной сложности. 
  Сам скрипт написан очень хорошо - выделены функции, имена переменных понятны, PEP8 присутствует. Отлично!

2023-04-22 08:54 UTC, PhySci commented on src/parser/vseti.py
> +driver = webdriver.Chrome()
Может быть занести эту инициализацию драйвера в функцию main? Точно ли надо это делать здесь?

2023-04-22 08:54 UTC, PhySci commented on src/parser/vseti.py
> +# driver = set_driver()
Можно вот так определять  ОС и решать, запускать инициализацию драйвера или нет
https://stackoverflow.com/questions/1854/how-to-identify-which-os-python-is-running-on

2023-04-22 08:54 UTC, PhySci commented on src/parser/vseti.py
> +    """opens a link for each vacancy and retrieves information about the vacancy description
Лайк за подробные комментарии.

2023-04-22 08:54 UTC, PhySci commented on src/parser/vseti.py
> +    except requests.exceptions.RequestException as e:
Может быть поднять except до 64 строки, чтобы он действовал только на requests.get(). Тогда станет чуть понятнее, что именно ловит этот try.

2023-04-22 08:54 UTC, PhySci commented on src/parser/vseti.py
> +    if element:
Вот здесь у тебя два вложенных if - это увеличивает сложность понимания. Хорошо бы применить "ранный выход", т.е. ты проверяешь условие и если оно верно, то сразу выходишь, а иначе продолжаешь работу. Так ты избавляешь от "вложенной" логики.

```
if element is None:
    logging.info(...)
    return ''

if attribute:
    return element.get(attribute)
else:
    return element.text.strip()    
```

2023-04-22 08:54 UTC, PhySci commented on src/parser/vseti.py
> +    try:
Два вложенных try-except - это прямо нехорошо, потому что сложно для понимания и могут как-то странно себя повести. Давай объединим их в один.
```
try:
    driver.get(url)
    driver.maximize_window()
    sleep(60)
    driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
    sleep(60)
     jobs = driver.find_elements(By.XPATH, "//div[@class='collection-item w-dyn-item']")
except NoSuchElementException as e
  some code here
except WebDriverException as e
 some code here  
```

2023-04-22 08:54 UTC, PhySci commented on src/parser/vseti.py
> +    period = date.today() - timedelta(days=int(args['days']))
А как переменная args попадает сюда?

2023-04-22 08:54 UTC, PhySci commented on src/parser/vseti.py
> +def main(args):
Давай вместо одной входной переменной args заведём две:
- filename
- days

и будем распаковывать эти переменные при вызове main. Так будет понятнее, какие именно аргументы принимает main
т.е.

```
def main(filename, days):
   ...
   
 if __name__ == '__main__':
    setup_logging("log.txt")
    args = parse_args()
    main(args["filename"], args["days"])  
```

2023-04-23 16:47 UTC, EkaterinaTerentyeva commented on src/parser/vseti.py
> +    if element:
Здесь я не уверена что правильно сделала

2023-04-23 17:21 UTC, PhySci commented on src/parser/vseti.py
> +    if attrs:
А может быть этот if совсем не нужен?
Если оставить только 
```
element = soup.find(tag, attrs) 
```
то при пустом attrs будет выполнять так, будто это
```
soup.find(tag) 
```

2023-04-23 17:22 UTC, PhySci approved these changes

2023-04-23 17:22 UTC, PhySci commented
Well done!

2023-04-23 17:22 UTC, merged

2023-04-23 20:57 UTC, EkaterinaTerentyeva commented on src/parser/vseti.py
> +    if attrs:
Я вот уже не помню почему, но почему то такой вариант у меня с треском грохался
Можно, конечно, вот так написать (исключительно для любителей красоты)
element = soup.find(tag, attrs) if attrs else soup.find(tag)
if not element:
        logging.info(f'bla-bla-bla}')
        return ''
return element.get(attribute) if attribute else element.text.strip()