Add files via upload
dataMasterskaya/DreamParser pull request #7
Opened 2023-04-22 11:05 UTC by Saponjyan

2023-04-22 11:05 UTC, Saponjyan commented
rfdgtd

2023-04-23 16:25 UTC, PhySci requested changes

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +    display = Display(visible=0, size=(1920, 1200))
Инициализацию драйвера лучше в отдельный файл

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +    urls = {'United States':
Может быть вынести этот словарь в JSON файл и вычитывать его?

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +
Две пустые строки лучше заменить на одну.

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +
Аналогично здесь - несколько пустых строк заменяем на одну.

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +            jobTitle = None
Вместо None здесь лучше использовать пустую строку.

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +
Предлагаю подключить линтер к VSCode

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +            company_field = driver.find_element(By.XPATH,("/html/body/div[2]/div/div/div/"
Может быть у этого поля есть какое-то уникальное название. Боюсь, вся конструкция поедет при незначительном изменении вёрстки страницы.

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +            sleep(0.1)
Давай здесь и далее, во всех except будем добавлять сообщение в логгер с уровнем warning.

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +            employerName = None
logger.warning()

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +
logger.warning()

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +        for i in jt:
Обычно переменные с односложными именами _i_, _j_, _k_ используются для счётчиков (1, 2, 3...). Давай здесь вставим чуть более содержательное имя переменой?

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +    def scan(cont,alllink):
Хорошо бы вынести эту функцию из main

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +            #print(repr(ex),"нет вакансии")
logger.warning()

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +        w = csv.writer(f)
Пожалуй, хорошо бы добавить заголовок для csv файла.

2023-04-23 16:25 UTC, PhySci commented on src/parser/glassdoor.py
> +    main()
Мог бы добавить инициализацию логгера из utils перед вызовом main()?

2023-04-28 20:47 UTC, PhySci approved these changes
Fine!

2023-04-28 20:47 UTC, merged