Скрипт работает, проверял несколько раз.
dataMasterskaya/DreamParser pull request #8
Opened 2023-04-22 12:25 UTC by NikitaMetelev

От pandas  избавился, функции 2 написал

2023-04-23 16:37 UTC, PhySci requested changes
Отличный скрипт!
 Оставил несколько минорных комментариев по структуре кода.

2023-04-23 16:37 UTC, PhySci commented on src/parser/dice.com.py
> +    driver = webdriver.Chrome("chromedriver", options=options)
Давай выбор опций и инициализацию драйвера вынесем в отдельную функцию?

2023-04-23 16:37 UTC, PhySci commented on src/parser/dice.com.py
> +            skills = None
В качестве заполнителя пропущенных значений лучше использовать пустую строку.

2023-04-23 16:37 UTC, PhySci commented on src/parser/dice.com.py
> +            del row['info_another']
Если в предыдущей строчке использовать row.pop("info_another"), то удаление не потребуется.

2023-04-23 16:37 UTC, PhySci commented on src/parser/dice.com.py
> +    with open(f'dice.com_{datetime.now().strftime("%Y-%m-%d-%H-%M")}', mode="w", encoding='utf-8') as w_file:
Мог бы обернуть запись в файл в отдельную функцию и перенести её в utils?
Тогда твои одногруппники смогли бы тоже ей воспользоваться. Подумай, какие параметры они захотят передавать.

2023-04-24 15:11 UTC, NikitaMetelev commented on src/parser/dice.com.py
> +    driver = webdriver.Chrome("chromedriver", options=options)
Сделал

2023-04-24 15:12 UTC, NikitaMetelev commented on src/parser/dice.com.py
> +            skills = None
Убрал None

2023-04-24 15:14 UTC, NikitaMetelev commented on src/parser/dice.com.py
> +            del row['info_another']
Мне нужно удалить все строки ['info_another'], после того, как подтяну из них информацию в пустующий ['description'] 
Не только те, что удовлетворяют условию

2023-04-24 15:15 UTC, NikitaMetelev commented on src/parser/dice.com.py
> +    with open(f'dice.com_{datetime.now().strftime("%Y-%m-%d-%H-%M")}', mode="w", encoding='utf-8') as w_file:
Сделал функцию, перенёс в utils

Спасибо за ревью, учусь потихоньку делать правильно!

2023-04-27 09:27 UTC, NikitaMetelev commented on src/parser/dice.com.py
> +    driver = webdriver.Chrome("chromedriver", options=options)
Проверь, плиз

2023-04-27 09:28 UTC, NikitaMetelev commented on src/parser/dice.com.py
> +            skills = None
Сделал правильную пустую строку

2023-05-06 18:50 UTC, PhySci approved these changes
Nice!

2023-05-06 18:52 UTC, merged